# Generated by Django 3.2.25 on 2025-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='overwrite_data',
            field=models.BooleanField(default=False),
        ),
    ]
