# Generated by Django 3.2.25 on 2025-02-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_overwrite_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='overwrite_data',
        ),
    ]
