# Generated by Django 3.2.25 on 2025-02-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_books_overwrite_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price_audiobook',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price_hardcover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price_softcover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
