# Generated by Django 5.2.6 on 2025-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_email_sent_order_webhook_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('', 'Select Country'), ('GB', 'United Kingdom'), ('US', 'United States'), ('IE', 'Ireland'), ('FR', 'France'), ('DE', 'Germany'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('CA', 'Canada'), ('NZ', 'New Zealand'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland')], max_length=2),
        ),
    ]
